### PR TITLE
Modernized PHPUnit implementation

### PR DESCRIPTION
**Pull request by mikevandiepen**
PHPUnit is now dependend on composer, this means less files in the project and an easier implementation.

### CODE REVIEW

**Comment by JKetelaar** [comment]
Thank you! I haven't had a response back from KiyOh unfortunately, so this Travis will still fail... Not entirely sure how to approach this. I will think about it over the weekend.

Best wishes

**Comment by JKetelaar** [comment]
Is this pull requests dependent on #24? You mention _"PHPUnit is now dependend on composer"_, but I don't see any changes in the composer.json file in this pull request.

**Comment by mikevandiepen** [comment]
No, before we used to have a autoload.php file inside /tests. This file has been removed since PHPUnit will now use the composer autoload. I implement phpunit in several of my own projects this way, you can checkout my repo's in case you'd like to dig deeper into it.

**Comment by JKetelaar** [comment]
This isn't working, or I am missing something.

When I run the command myself (` vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml`), I get the following output:
```
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.

Usage: phpunit [options] UnitTest [UnitTest.php]
       phpunit [options] <directory>
```

And it does not execute any tests.

Same for the `after_script` command you added (`php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.xml`):
```
Could not open input file: vendor/bin/ocular
```

Are you sure there are no changes needed to the `composer.json` file?

**Comment by mikevandiepen** [comment]
I'll take a look into it tomorrow!

**Comment by mikevandiepen** [comment]
Strange.. `vendor\bin\phpunit --coverage-text --coverage-clover=coverage.xml` works for me, ocular errors indeed.

**Comment by mikevandiepen** [comment]
My fault, Ocular was an instance used by scrutinizer. I use both Scrutinizer and Travis in my projects so I didn't think much of it and copied it over from my own repo.

Updated the PR without `after_script`.

**Comment by JKetelaar** [comment]
Got it working, thank you!

**Pull request merged**
