### PR TITLE
Feature/support php8 only

### PR DESCRIPTION
**Pull request by fruitl00p**
this is the last and (currently) final MR to drop PHP7 entirely. 
I suspect you'd like to release an intermediate PHP7 supporting release first and then bump the semver major to only support php8+ in the future.

### CODE REVIEW

**Comment by JKetelaar** [comment]
That said, maybe it's a good idea to release this as v3.0 instead of v2.0, to ensure systems using this module don't get broken.

**Comment by fruitl00p** [comment]
I understand. 7.4 will reach EOL this month I believe.. 

Would be great to have atleast 7.4 and up as the last 7 release and then push for a 8+ branch and keep development there. That way clients relying on php7 can always stick to the older branch/release. 

Love semver :)

**Comment by fruitl00p** [comment]
@JKetelaar any possible update on this PR (and/or the Guzzle update to atleast get Drupal10 compatibility)

**Comment by JKetelaar** [comment]
Hi there - thanks for the headsup. I'll merge this PR, thanks a lot.
Due to PHP 7.4 now being out of support, I don't think we have to worry too much about that version anymore.

**Pull request merged**
