### PR TITLE
Php 74

### PR DESCRIPTION
**Pull request by mikevandiepen**
I updated the project to fit PHP 7.4, implemented property types, Coalesce assignment operator instead of if statement etc. Please review the code, I did this on the fly, i'm pretty sure it works but don't take my word for it.

I also implemented StyleCI and TYPHP. Libraries for validating the code style and strictness.

### CODE REVIEW

**Comment by mikevandiepen** [comment]
I recommend to keep this as a 7.4 branch since it is not widely used yet.

**Comment by JKetelaar** [comment]
Loving the change! But this is breaking backward compatibility. I will merge this into a development branch and add backward compatibility with deprecation notices.

**Comment by JKetelaar** [comment]
Wouldn't this also mean to remove all php < 7.3 support?

**Comment by mikevandiepen** [comment]
Yes, all previous PHP versions become obsolete. All versions prior to 7.4 will error on typed properties. And I reckon that all the versions prior to 7.1 do not support class constant visibility. I'd recommend to just maintain two separate branches but develop on the 7.1 branch, this 7.4 branch is mainly for more modern projects. We'll be a long way ahead before 7.4 is widely used and implemented.

**Comment by JKetelaar** [comment]
Alright, thanks for the information. I will think about what to do with this, as I cannot really imagine people **needing** a 7.4 version, and having us to maintain two different branches at the same time. It seems like a bit of overhead. For now, I am leaning towards waiting until PHP 7.3 is not supported anymore ([_in 1 year, 11 months_](https://www.php.net/supported-versions.php)).

Nonetheless, I really like the changes you did to the naming, so I will at least include those in a refactor that does not have to wait for PHP 7.4.

**Pull request closed without merging**
